### ISSUE TITLE
Should this work with Rails 3.0?

### ISSUE THREAD

**Issue by ryanpool** [envato/rails_4_session_flash_backport#13]
When trying to use in an application I'm upgrading from 2.3.18 to 3.0.20 I'm getting an uninitialized constant ActionDispatch::Flash::KEY in lib/rails_4_session_flash_backport/rails3/flash_hash.rb:58:in `ensure in call' while on Rails 3.0.20.  This is with v0.1.0 of rails_4_session_flash_backport.

It doesn't look like ActionDispatch::Flash::KEY is defined in 3.0, just in 3.1 and 3.2.

**Comment by joneslee85** [comment]
@ryanpool would you mind submit a PR and please also add in Rails 3.0 testing in `/gemfiles`? Much thanks

**Comment by joneslee85** [comment]
I've created [test suites](https://travis-ci.org/envato/rails_4_session_flash_backport) against all Rails versions and it seems to me at this stage it fails on 3.0.

We will look into it further. Thanks for reporting

**Comment by sj26** [comment]
Quite right, we've never explicitly supported 3.0.

So it turns out rails 3.0 used something between rails 2.x and 3.1's solution. Here's a partial implementation: https://github.com/envato/rails_4_session_flash_backport/compare/rails-3-0-support Unfortunately I don't think we can achieve full compatibility.

In rails 3.0 the FlashHash still descends from Hash. This means it's marshalled as a user_class descending from hash, not a plain object, so unmarshalling existing values to migrate will fail. If you've already had this gem installed since 2.3 it should be seamless. But if you start on 3.0 and go to 3.1 I think you must just lose your sessions/flashes anyway. How have we handled this in the past?

Migration from 2.3 to 3.1 is easy because we can just put a Hash descendent class where Marshal expects it to be, but 3.0 uses the same name as 3.1 for a class which no longer inherits from Hash.

Here's a gist of the marshal streams for reference: https://gist.github.com/sj26/75b3a18c0c8854e562e1

**Comment by ryanpool** [comment]
Hi all.  On my system I'm now getting a dynamic constant assignment syntax error on the KEY = 'action_disp' line.  Any thoughts?

**Comment by sj26** [comment]
That's very strange. What version of ruby are you using?

**Comment by ryanpool** [comment]
Sorry didn't see this.  I have the problem in Ruby 2.0.0 for sure.  I believe I also have it in 1.9.3, but I'll have to go back and check.

I know Rails 3.0 and Ruby 2.0 make for an unsupported combination but this is a very old application that is being updated from Ruby 1.8.7 and Rails 2.3 up to something reasonable.
